%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters (fixed).
#--------------------------------------------------------------------------------------------
# original image size for camera
width: 240
height: 180

#--------------------------------------------------------------------------------------------
# Event Parameters (tunable).
#--------------------------------------------------------------------------------------------
# size of real targets
Event.delta_time: 0.0001
Event.max_event: 1e5
